# This is a basic workflow to help you get started with Actions

name: Builds and publish this project
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/cache@v2
        with:
          path: 'thirdparty'
          key: ${{ runner.os }}-modules-${{ hashFiles('thirdparty/build-opencv.sh') }}

      - name: Install dependencies
        run: npm install

      - name: Build WASM
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: example
          CLEAN: true

